model:
  name: gemma-3-4b-it
  type: gemma-3
  path: google/gemma-3-4b-it
  tensor_parallel_size: 1 # TODO: test
  dtype: bfloat16
  reasoning: false
  max_new_tokens: 2048
  temperature: 1.0
  top_k: 64
  top_p: 0.95
  min_p: 0.0