model:
  name: Qwen2.5-3B-Instruct
  type: Qwen
  path: Qwen/Qwen2.5-3B-Instruct
  tensor_parallel_size: 1
  dtype: bfloat16
  reasoning: false
  max_new_tokens: 2048
  temperature: 0.7
  top_p: 0.8
  top_k: 20
  min_p: 0.0

