datasets:
  math_500: 
    train: "/n/netscratch/ydu_lab/Lab/alex/MATH/unique_ids_train.json"
    test: "/n/netscratch/ydu_lab/Lab/alex/MATH/unique_ids_test.json"
    verifiers:
      - "math_steps"
      - "units_steps"
      - "general_summarize"
      - "general_edge"
      - "general_mistakes"
      - "general_domain" 
  math:
    train: "/n/netscratch/ydu_lab/Lab/alex/MATH/train/**/*.json"
    test: "/n/netscratch/ydu_lab/Lab/alex/MATH/test/**/*.json"
    verifiers:
      - "math_steps"
      - "units_steps"
      - "general_summarize"
      - "general_edge"
      - "general_mistakes"
      - "general_domain" 