# Default configuration for LMVF evaluation

# Model settings
# model: "deepseek-r1-distill-qwen-1.5b"  # Main model for generation
model: "Qwen2.5-0.5B-Instruct" # "gemma-3-1b-it" #"Qwen2.5-0.5B-Instruct"
# verifier_model: "Qwen2.5-0.5B-Instruct"
# strict_verifier_model: "Qwen2.5-0.5B-Instruct"

# verifier_model: null    # Optional separate model for verification (uses main model if null)
verifier_model: "deepseek-r1-distill-qwen-1.5b" # "gemma-3-1b-it" # "deepseek-r1-distill-qwen-1.5b"
strict_verifier_model: "Qwen2.5-3B-Instruct"

# Other settings
seed: 42
gpus_per_node: 1
num_nodes: 2

# Dataset settings
dataset: "math"

# Generation settings
num_generations: 4
batch_size: 64
verifier_batch_size: 16

# Evaluation settings
eval_mode: 
    - "pass@1"
    - "pass@4"
    - "bon-mav"
verbose: false

# Output settings
output_base_path: "/n/netscratch/hankyang_lab/Lab/alex/LMVF"