# Default configuration for LMVF generation

# Model settings - can be a single model or list of models
# model: "deepseek-r1-distill-qwen-1.5b"  # Main model for generation
# model: "Qwen2.5-0.5B-Instruct" # "gemma-3-1b-it" #"Qwen2.5-0.5B-Instruct"
# Example with multiple models:

# Base configuration - shared across all evaluations
base_config:
  models:
    - "Qwen2.5-0.5B-Instruct" # trial 1
    - "Qwen2.5-1.5B-Instruct" # trial 1
    - "Qwen2.5-3B-Instruct" # trial 1
    # - "Qwen2.5-7B-Instruct" # trial 1
    # - "gemma-3-1b-it" # trial 2
    # - "Qwen2.5-0.5B-Instruct" # trial 2
    # - "Qwen2.5-1.5B-Instruct" # trial 2
    # - "Qwen2.5-3B-Instruct" # trial 2
    # - "Qwen2.5-7B-Instruct" # trial 2
    # - "Qwen2-0.5B-Instruct" # trial 2
    # - "Qwen2-1.5B-Instruct" # trial 2
  
  seed: 42
  gpus_per_node: 1 # Ignored if running straight from the python script
  num_nodes: 2 # Ignored if running straight from the python script

  dataset: "math_500"

  num_generations: 8
  batch_size: 64
  output_base_path: "/n/netscratch/ydu_lab/Lab/alex/LMVF"
  output_file_name: "task_{task_id}_solutions_trial_4.json"
  verbose: false