# Default configuration for LMVF evaluation

# Model settings
model: "Qwen2.5-0.5B-Instruct"
# verifier_model: "Qwen2.5-0.5B-Instruct"
# strict_verifier_model: "Qwen2.5-0.5B-Instruct"

# verifier_model: null    # Optional separate model for verification (uses main model if null)
verifier_model: "Qwen2.5-3B-Instruct"
strict_verifier_model: "Qwen2.5-3B-Instruct"

# Other settings
seed: 42
gpus_per_node: 1
num_nodes: 1

# Dataset settings
dataset: "math"

# Generation settings
num_generations: 2
batch_size: 2
# verifier_batch_size: 2

# Evaluation settings
eval_mode: 
    # - "pass@1"
    # - "pass@2"
    - "borda"
    # - "bon-mav"
verbose: false

# Output settings
output_base_path: "/n/netscratch/hankyang_lab/Lab/alex/LMVF"
